name = "JuliaOS"
uuid = "12345678-1234-5678-1234-567812345678"
authors = ["JuliaOS Contributors <contributors@juliaos.org>"]
version = "0.1.0"

[deps]
# Core server essentials  
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Oxygen = "df9a0d86-3283-4920-82dc-4555fc0d1d8b"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
WebSockets = "104b5d7c-a370-577a-8038-80a2059c5097"

# Standard library (no precompilation cost)
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

# Essential functionality deps
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
LRUCache = "8ac3fa9e-de4c-5943-b1dc-09c6b5f20637"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Redis = "0cf705f9-a9e2-50d1-a699-2b372a39b750"
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"

[sources]
HTTP = {url = "https://github.com/JuliaWeb/HTTP.jl"}
Redis = {url = "https://github.com/JuliaDatabases/Redis.jl"}

[compat]
HTTP = "1"
JSON = "0.21"
JSON3 = "1"
LRUCache = "1"
Oxygen = "1"
StructTypes = "1"
DataStructures = "0.18"
PyCall = "1"
Redis = "1"
SQLite = "1"
WebSockets = "1"
julia = ">=1.8"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "BenchmarkTools"]
